# Generated by Django 5.0.6 on 2024-07-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_add_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_cart',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='add_cart',
            name='t',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
