# Generated by Django 5.0.6 on 2024-07-03 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_add_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.user'),
        ),
    ]
