# Generated by Django 5.0.7 on 2024-07-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='cupan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupan', models.CharField(max_length=6)),
                ('discount', models.IntegerField()),
                ('expier', models.DateTimeField()),
            ],
        ),
    ]
