# Generated by Django 5.0.7 on 2024-07-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_rename_cupan_cupan_c_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupan',
            old_name='c_code',
            new_name='cupan_code',
        ),
    ]
