# Generated by Django 5.0.7 on 2024-07-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_rename_c_code_cupan_cupan_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupan',
            name='cupan_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
