# Generated by Django 5.0.7 on 2024-07-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_reart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reart',
            new_name='rateing',
        ),
    ]
