# Generated by Django 5.0.7 on 2024-07-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_rename_reart_rateing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rateing',
            old_name='ret',
            new_name='rate',
        ),
    ]
