# Generated by Django 5.0.7 on 2024-08-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_billing_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_address',
            name='country',
        ),
    ]
