# Generated by Django 5.0.7 on 2024-08-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_user_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
    ]
