# Generated by Django 5.0.7 on 2024-08-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_order_phone_order_zipcode_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cupan',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
