# Generated by Django 5.0.7 on 2024-08-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_order_cupan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupan',
            name='aply',
            field=models.BooleanField(default=True),
        ),
    ]
